import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
    build: {
        lib: {
            entry: resolve(__dirname, 'server/index.ts'),
            formats: ['es'],
            fileName: 'index',
        },
        rollupOptions: {
            external: [
                'express',
                'cors',
                'cheerio',
                '@anthropic-ai/sdk',
                'openai',
                '@mozilla/readability',
                'vite',
                // Node.js built-ins
                'util',
                'path',
                'fs',
                'os',
                'crypto',
                'stream',
                'http',
                'https',
                'url',
                'zlib',
                'events',
                'assert',
                'buffer',
                'querystring',
                'net',
                'tls',
                'dns',
                'http2',
                'https',
                'worker_threads',
                'diagnostics_channel',
                'perf_hooks',
                'async_hooks',
                'vm',
                'timers',
                'console',
                // undici and its dependencies
                'undici',
                'node:util',
                'node:events',
                'node:http',
                'node:https',
                'node:net',
                'node:tls',
                'node:assert',
                'node:stream',
                'node:util/types',
                'node:buffer',
                'node:querystring',
                'node:dns',
                'node:zlib',
                'node:fs',
                'node:path',
                'node:async_hooks',
                'node:worker_threads',
                'node:diagnostics_channel',
                'node:perf_hooks',
                'node:vm',
                'node:timers',
                'node:console',
                'node:crypto',
                'node:net',
                'node:http2',
                'node:sqlite',
            ],
            output: {
                entryFileNames: 'index.js',
            },
        },
        outDir: 'dist/server',
        emptyOutDir: true,
        target: 'node22',
        minify: false,
        sourcemap: true,
    },
    server: {
        port: 3001,
    },
});
